apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - image: registry.nz.thenational.com/rfod/pause:3.5
      imagePullPolicy: Always
      name: pause
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 512Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
  securityContext:
    fsGroup: 1001
    runAsGroup: 0
    runAsNonRoot: true
    runAsUser: 1001
    seccompProfile:
      type: RuntimeDefault
    supplementalGroups:
    - 1001
